#! /bin/bash

echo "Build 👷"

ROOT=$(git rev-parse --show-toplevel)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ $BRANCH == "master" ]; then
  echo "building master branch"
  cmd=$(jq -r .steps.deploy "${ROOT}/.fake-ci.json")
  echo $cmd
  $cmd
  # eval $(jq .steps.deploy "${ROOT}/.fake-ci.json")
fi