#! /bin/bash

echo "=== Fake CI ==="

ROOT=$(git rev-parse --show-toplevel)

echo "--- Deploy ---"
cmd=$(jq -r .steps.deploy "${ROOT}/.fake-ci.json")
echo $cmd
$cmd

echo "--- Test ---"
cmd=$(jq -r .steps.deploy "${ROOT}/.fake-ci.json")
echo $cmd
$cmd